### ISSUE TITLE
Alternate way to populate the Gene Studied OBX

### ISSUE THREAD

**Issue by Rohan-cod** [elimuinformatics/vcf2hl7v2#6]
## Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

* Package Version: latest
* Operating System: macOS

## Expected Behavior

The **file**([`geneKB_Gene_table.csv`](https://github.com/elimuinformatics/vcf2hl7v2/blob/master/vcf2hl7v2/geneKB_Gene_table.csv)) is too large to be submitted with the binary. Think of a way to optimize the usage of this file or an alternate way to populate the **Gene Studied OBX**.

## Current Behavior

The current code uses the gene [`geneKB_Gene_table.csv`](https://github.com/elimuinformatics/vcf2hl7v2/blob/master/vcf2hl7v2/geneKB_Gene_table.csv) to populate the **Gene Studied OBX**.

**Comment by rhdolin** [comment]
@Rohan-cod Design document has been revised. We'll pull the gene name from the annotation file. We can get rid of the geneKB table.
